name: Trigger auto deployment for myaca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/myaca-AutoDeployTrigger-99f5aaf5-39c2-423f-979d-79e5a0c9554a.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYACA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: myacrforapp.azurecr.io
          registryUsername: ${{ secrets.MYACA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYACA_REGISTRY_PASSWORD }}
          containerAppName: myaca
          resourceGroup: abc
          imageToBuild: myacrforapp.azurecr.io/centos:${{ github.sha }}
          

     

